
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mkp_web?useSSL=true&serverTimezone=Asia/Bangkok
    username: root
    password: password

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none

